CREATE TABLE IF NOT EXISTS cidades (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (255) NOT NULL,
    ESTADO_ID INT UNSIGNED NOT NULL,
    AREA DECIMAL (10,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID_ESTADO)
);

ALTER TABLE cidades MODIFY ESTADO_ID INT (10) UNSIGNED NOT NULL;

INSERT INTO cidades
    (NOME, ESTADO_ID, AREA)
VALUES
    ('Londrina', (SELECT ID_ESTADO FROM ESTADO WHERE NOME = 'Paraná'), 1.651);

INSERT INTO cidades
    (NOME, ESTADO_ID, AREA)
VALUES
    ('Ibipora', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'Paraná'), 300.187),
    ('Cambe', (SELECT ID_ESTADO  FROM `ESTADO` WHERE NOME = 'Paraná'), 495.4),
    ('Sao Paulo', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'São Paulo'), 1.521),
    ('Juazeiro', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'Bahia'), 6.501),
    ('Colatina', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'Espírito Santo'), 1.417),
    ('Presidente Prudente', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'São Paulo'), 592.794),
    ('Rio de Janeiro', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'Rio de Janeiro'), 1.225),
    ('Fortaleza', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'Ceará'), 313.8),
    ('Manaus', (SELECT ID_ESTADO FROM `ESTADO` WHERE NOME = 'Amazonas'), 11.401)
    ;
