CREATE TABLE IF NOT EXISTS prefeitos (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (255) NOT NULL,
    CIDADE_ID INT UNSIGNED,
    PRIMARY KEY (ID),
    FOREIGN KEY (CIDADE_ID) REFERENCES cidades (ID)
)